### PR TITLE
Support Mongoid 5.0

### PR DESCRIPTION
**Pull request by amw**
I think this is a more complete version of #57. Thanks to @kierangraham for starting the work on this.

### CODE REVIEW

**Comment by sferik** [comment]
Can you please update the Travis CI build matrix to test against Mongoid 5? Also, can you please rebase from master to pick up fixes for the RuboCop issues?

**Comment by amw** [comment]
I've added Mongoid 5 to the Travis matrix and also rebased against current master.

RuboCop has required that self.reserve be less than 15 lines of code so I had to split it into two methods. I don't think this makes it more readable as a whole. Maybe that limit is too restrictive? I would suggest dropping that commit and going with a longer, but easily understandable method.

I had to adjust coverage threshold, because I have conditional logic that branches on Mongoid version. A single Travis run cannot test both branches, but given a complete Travis matrix the commits are fully covered.

Please note that Travis reports errors, but that's also true for your master branch. All the tests that pass on master also pass on my pull request now.

**Comment by sferik** [comment]
> I've added Mongoid 5 to the Travis matrix and also rebased against current master.

Perfect. Thanks!

> RuboCop has required that self.reserve be less than 16 lines of code so I had to split it into two methods. I don't think this makes it more readable as a whole. Maybe that limit is too restrictive? I would suggest dropping that commit and going with a longer, but easily understandable method.

We’ve found the 15-line method limit to be a good rule-of-thumb to prevent methods from spiraling out of control. It’s possible to disable in case where we want to override it but, personally, I think the extracted method `reservation_criteria` actually makes things clearer. Thanks for doing this refactoring.

> I had to adjust coverage threshold, because I have conditional logic that branches on Mongoid version. A single Travis run cannot test both branches, but given a complete Travis matrix the commits are fully covered.

Understood. No problem.

> Please note that Travis reports errors, but that's also true for your master branch. All the tests that pass on master also pass on my pull request now.

I’m going to merge this and look into those error now.

Thanks again for your contribution!

**Comment by dblock** [comment]
Needs a line in CHANGELOG too and a release, please! Thanks, awesome job.

**Comment by dblock** [comment]
Also https://github.com/dblock/mongoid-compatibility might help, I've been copy pasting a lot of version comparison code all over the place too ...

**Pull request merged**
