### PR TITLE
Extract out mixin to enable better backend customization

### PR DESCRIPTION
**Pull request by johnnyshields**

### CODE REVIEW

**Review by dblock — CHANGES_REQUESTED** [review]
1. Does inheriting from `Job` and using `store_in` not work without this change?
2. Add a test that ensures that the README example, ie. using `store_in` does what you want it to do.

**Comment by johnnyshields** [comment]
@dblock to answer #1, it doesn't work; it [raises an `InvalidStorageParent` error](https://github.com/mongodb/mongoid/blob/af797ed8b3803898d20b5dc997c4f3e941b5a9a9).

**Comment by dblock** [comment]
Want to add that test @johnnyshields? Or just merge?

**Comment by johnnyshields** [comment]
@dblock done and merging when specs pass.

**Pull request merged**
