### PR TITLE
Feature/mongoid 7 compatibility

### LINKED ISSUE #74: Mongoid 7 support
Are there any plans to support Mongoid 7?

### PR DESCRIPTION
**Pull request by Startouf**
Fixes #74

### CODE REVIEW

**Comment by Startouf** [comment]
Specs were green after the changes when running rspec locally on ruby 2.5.1

**Comment by jafuentest** [comment]
@Startouf I updated the changelog and readme for you and sent a PR to your fork =)

**Comment by dblock** [comment]
@jafuentest You can redo a PR here if you want with @Startouf's changes

**Comment by jafuentest** [comment]
Done, #78

**Comment by Startouf** [comment]
Hey thanks, I've merged the PR on my side, so I guess we could close either this PR or #78

**Comment by Startouf** [comment]
I have activated Travis on my repo, the PR is building there : https://github.com/Startouf/delayed_job_mongoid/pull/2

**Comment by dblock** [comment]
@Startouf Let's see if we can get hold of @sferik or @albus522 and get some more admin hands on this repo?

I am one of the rubygems owners so if anything we can fork, but I'd prefer not to.

**Comment by dblock** [comment]
Btw, this was discussed in https://github.com/collectiveidea/delayed_job_mongoid/issues/70, let me see if I can get someone's attention over email.

**Comment by dblock** [comment]
Closing in favor of https://github.com/collectiveidea/delayed_job_mongoid/pull/78

**Comment by dblock** [comment]
I've released 2.3.1 with Mongoid 7 support.

**Pull request closed without merging**
